### ISSUE TITLE
Create Wireframe of App 

### ISSUE THREAD

**Issue by kbnewlon** [kbnewlon/project3#2]
As a developer
I want to have a wireframe of the site
So that I can build a responsive app with a good design

Acceptance Criteria:

- [x] Pick different wireframe app
- [x] Draft wireframe presented to team
- [x] Approval of Final Draft
- [x] Added to Readme.md

**Comment by crowandrew** [comment]
https://excalidraw.com/#room=b1c091692facb009f827,mtNgkMwmwNdIwSuy8ka_UA
